"""add is_confirmed to business knowledge

Revision ID: 111806efc121
Revises: a270094c53a1
Create Date: 2026-08-20 17:38:15.715472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111806efc121'
down_revision: Union[str, Sequence[str], None] = 'a270094c53a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_knowledge', sa.Column('is_confirmed', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_knowledge', 'is_confirmed')
    # ### end Alembic commands ###
