"""add onboarding messages

Revision ID: 6691006d7bc2
Revises: a7500e794f28
Create Date: 2026-08-19 19:53:30.996495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6691006d7bc2'
down_revision: Union[str, Sequence[str], None] = 'a7500e794f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_messages_agent_id'), 'onboarding_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_onboarding_messages_id'), 'onboarding_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_messages_id'), table_name='onboarding_messages')
    op.drop_index(op.f('ix_onboarding_messages_agent_id'), table_name='onboarding_messages')
    op.drop_table('onboarding_messages')
    # ### end Alembic commands ###
