"""create customer messages

Revision ID: 7f6a09d64a3a
Revises: 111806efc121
Create Date: 2026-08-20 19:02:24.446074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6a09d64a3a'
down_revision: Union[str, Sequence[str], None] = '111806efc121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_messages_agent_id'), 'customer_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_customer_messages_id'), 'customer_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_messages_id'), table_name='customer_messages')
    op.drop_index(op.f('ix_customer_messages_agent_id'), table_name='customer_messages')
    op.drop_table('customer_messages')
    # ### end Alembic commands ###
