"""add business profile knowledge models

Revision ID: d0a0949ca0d5
Revises: 5624179bc13e
Create Date: 2026-08-28 21:49:46.191129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a0949ca0d5'
down_revision: Union[str, Sequence[str], None] = '5624179bc13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_agent_id'), 'business_profiles', ['agent_id'], unique=True)
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_agent_id'), 'knowledge_sources', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_id'), 'knowledge_sources', ['id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_agent_id'), 'knowledge_entries', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_source_id'), 'knowledge_entries', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_entries_source_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_agent_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_knowledge_sources_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_agent_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_agent_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
